version: 0.0
os: linux

# Define the name of the application and the location of the files
files:
  - source: /
    destination: /var/www/html

# Define the hooks for the deployment lifecycle
hooks:
  AfterInstall:
    - location: scripts/install_dependencies.sh
      timeout: 180
      runas: root
  ApplicationStart:
    - location: scripts/start_server.sh
      timeout: 180
      runas: root
  ApplicationStop:
    - location: scripts/stop_server.sh
      timeout: 180
      runas: root
