version: 0.2

phases:
  install:
    commands:
      - echo "No dependencies to install for a simple HTML/CSS app."

  pre_build:
    commands:
      - echo "Preparing build artifacts..."

  build:
    commands:
      - echo "Building the HTML/CSS app..."
      - mkdir -p build
      - cp -r * build/

  post_build:
    commands:
      - echo "Post build steps completed."
      - echo "No artifacts stored."
